# Generated by Django 5.0.3 on 2024-03-21 01:06

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[restaurant.models.validate_number]),
        ),
    ]
